services:
  ny_taxi_pg:
    image: postgres:18
    container_name: ny_taxi_pg
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ny_taxi_data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  data_pipeline:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    container_name: data_pipeline
    depends_on:
      ny_taxi_pg:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=ny_taxi_pg
      - POSTGRES_PORT=5432
      - UV_PROJECT_ENVIRONMENT=/opt/venv
      - UV_PYTHON_PREFERENCE=only-system
    volumes:
      - ./pipeline:/app
      - ./pipeline/processed:/app/processed
    restart: always
    command: >
      bash -c "
      cd /app &&
      uv sync --frozen &&
      uv run python -u load_parquet_to_postgres.py
      "

  jupyter:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    container_name: data_pipeline_jupyter
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=ny_taxi_pg
      - POSTGRES_PORT=5432
      - UV_PROJECT_ENVIRONMENT=/opt/venv
      - UV_PYTHON_PREFERENCE=only-system
    volumes:
      - ./pipeline:/app
    depends_on:
      ny_taxi_pg:
        condition: service_healthy
    ports:
      - "8888:8888"
    command: >
      bash -c "
      cd /app &&
      uv sync --frozen &&
      uv run jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
      "

  ingest_incremental:
    build:
      context: ./pipeline
      dockerfile: Dockerfile.ingest
    container_name: ny_taxi_ingest_incremental
    depends_on:
      ny_taxi_pg:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=ny_taxi_pg
      - POSTGRES_PORT=5432
    volumes:
      - ./output/logs:/logs
    restart: "no"
    # IMPORTANT: these are only script args (ENTRYPOINT runs ingestincremental.py)
    command:
      - "--from-release"
      - "yellow"
      - "--start-month"
      - "2019-01"
      - "--end-month"
      - "2021-12"
      - "--table"
      - "yellow_taxi_data"
      - "--chunk-size"
      - "50000"
      - "--retries-per-chunk"
      - "3"
      - "--retry-sleep-sec"
      - "2"
      - "--log-file"
      - "/logs/etl_batch.log"

volumes:
  ny_taxi_data:
