name: Docker Data Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pipeline-test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_HOST: ny_taxi_pg

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create .env file for Docker Compose
        run: |
          cat <<EOF > .env
          POSTGRES_USER=${POSTGRES_USER}
          POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          POSTGRES_DB=${POSTGRES_DB}
          POSTGRES_HOST=${POSTGRES_HOST}
          EOF

      - name: Build and start containers
        run: |
          docker compose up -d --build

      - name: Wait for Postgres to be healthy
        run: |
          sleep 20
          docker ps

      - name: Show pipeline logs
        run: |
          docker compose logs data_pipeline

      - name: Tear down containers
        if: always()
        run: |
          docker compose down -v
